version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
branches:
  only:
  - master
before_build:
- ps: >-
    Write-Host ("Installing MonoGame...")


    Start-Sleep -s 5
- cmd: >-
    dotnet restore

    nuget restore
build:
  parallel: true
  verbosity: minimal