//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emberpoint.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emberpoint.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string BatteryPower {
            get {
                return ResourceManager.GetString("BatteryPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        public static string Bed {
            get {
                return ResourceManager.GetString("Bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookcase.
        /// </summary>
        public static string Bookcase {
            get {
                return ResourceManager.GetString("Bookcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string Carpet {
            get {
                return ResourceManager.GetString("Carpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chair.
        /// </summary>
        public static string Chair {
            get {
                return ResourceManager.GetString("Chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desk.
        /// </summary>
        public static string Desk {
            get {
                return ResourceManager.GetString("Desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You closed the door..
        /// </summary>
        public static string DoorClosedEvent {
            get {
                return ResourceManager.GetString("DoorClosedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You opened the door..
        /// </summary>
        public static string DoorOpenEvent {
            get {
                return ResourceManager.GetString("DoorOpenEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed door.
        /// </summary>
        public static string DoorStateClosed {
            get {
                return ResourceManager.GetString("DoorStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open door.
        /// </summary>
        public static string DoorStateOpen {
            get {
                return ResourceManager.GetString("DoorStateOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashlight.
        /// </summary>
        public static string Flashlight {
            get {
                return ResourceManager.GetString("Flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emberpoint.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to interact..
        /// </summary>
        public static string InteractMessage {
            get {
                return ResourceManager.GetString("InteractMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybindings.
        /// </summary>
        public static string Keybindings {
            get {
                return ResourceManager.GetString("Keybindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp.
        /// </summary>
        public static string Lamp {
            get {
                return ResourceManager.GetString("Lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mysterious Voice.
        /// </summary>
        public static string MysteriousVoice {
            get {
                return ResourceManager.GetString("MysteriousVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing happens..
        /// </summary>
        public static string NothingHappens {
            get {
                return ResourceManager.GetString("NothingHappens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects in view.
        /// </summary>
        public static string ObjectsInView {
            get {
                return ResourceManager.GetString("ObjectsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a choice.
        /// </summary>
        public static string PickChoice {
            get {
                return ResourceManager.GetString("PickChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillar.
        /// </summary>
        public static string Pillar {
            get {
                return ResourceManager.GetString("Pillar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;{0}&apos; to continue.
        /// </summary>
        public static string PressConfirmToContinue {
            get {
                return ResourceManager.GetString("PressConfirmToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stairs down.
        /// </summary>
        public static string StairsDown {
            get {
                return ResourceManager.GetString("StairsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stairs up.
        /// </summary>
        public static string StairsUp {
            get {
                return ResourceManager.GetString("StairsUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statue.
        /// </summary>
        public static string Statue {
            get {
                return ResourceManager.GetString("Statue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wardrobe.
        /// </summary>
        public static string Wardrobe {
            get {
                return ResourceManager.GetString("Wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
